const stockInitState = {
    localStoreData: {},
    allStocksScripts: {},
    addedToBuyers: {},
    removedFromBuyers: {},
    addedToSellers: {},
    removedFromSellers: {},
    addedToBuyersSelective: {},
    filterSuddenValueGainer: {},
    extremeSuddenBuy: {},
    extremeSuddenSell: {},
    allVolatileStocks: [],
    largeCap: [],
    filterOpenInterest: {},
    onlyBuyersWithHighDemand: [],
    onlySellersWithHighDemand: [],
    dictDataFormat: {},
    dictSellerDataFormat: {},
    openInterest: {},
    refreshRate: '60',
    // selectedStocks: []
    // selectedStocksOld: ['JHS', 'HDIL', 'JIYAECO', 'SHIRPUR-G', 'TRIGYN', 'RELINFRA', 'RELHOME', 'INDINFO', 'ICICIBANK', 'BEL', 'TATASTLBSL', 'BCP', 'AVONMORE', 'SREEL', 'CONFIPET', 'SPAL', 'WELCORP', 'PRAJIND', 'BHEL', 'JBMA', 'ABFRL', 'SBIN', 'JAGRAN', 'KNRCON', 'ACE', 'HTMEDIA', 'HSCL', 'ONGC', 'GRAPHITE', 'DELTACORP*', 'WELENT', 'CANBK', 'BANKINDIA', 'GVKPIL', 'DHFL', 'EIHOTEL', 'SAFARIND', 'L&TFH', 'RECLTD', 'PNB', 'DBCORP', 'SHAILY', 'IOC', 'PSPPROJECT', 'WESTLIFE', 'RADIOCITY', 'VIPIND', 'JAMNAAUTO', 'MAHSEAMLES', 'MULTIBASE', 'FAZE3Q', 'RBLBANK', 'PCJEWELLER', 'ZENTEC', 'KITEX', 'SYNCOMF', 'MIRCELECTR', 'VIAANINDUS', 'SOUTHBANK', 'MUKANDLTD', 'SHRIRAMEPC', 'NATHIND', 'SAKSOFT', 'SNL', 'KGL', 'GICHSGFIN', 'SYNCOM', 'AIRAN', 'SRHHYPOLTD', 'V2RETAIL', 'INNOVATIVE', 'LASA', 'IBVENTURES']
    // newBought = ['AIRAN-BE', 'ANDHRAPET', 'CMICABLES', 'DELTACORP', 'ENGINERSIN', 'GAYAPROJ', 'KGL-BZ', 'LASA-BE', 'MAGMA', 'MENONBE', 'NITINSPIN', 'ORIENTBELL', 'RPOWER', 'SADBHAV', 'SCHAND', 'SYNCOM-BE', 'TECHNOFAB-BE', 'UNIPLY', 'VARDHACRLC']
    // selectedStocks: ['ABFRL', 'ACE', 'AIRAN', 'ANDHRAPET', 'AVONMORE', 'BCP', 'BEL', 'BHEL', 'CMICABLES', 'DBCORP', 'DELTACORP', 'EIHOTEL', 'ENGINERSIN', 'FAZE3Q', 'GAYAPROJ', 'GRAPHITE', 'GVKPIL', 'HSCL', 'HTMEDIA', 'INDINFO', 'INNOVATIVE', 'IOC', 'JAGRAN', 'JAMNAAUTO', 'JHS', 'JIYAECO', 'KGL', 'KITEX', 'KNRCON', 'LASA', 'MAGMA', 'MENONBE', 'MIRCELECTR', 'MUKANDLTD', 'MULTIBASE', 'NATHIND', 'NITINSPIN', 'ONGC', 'ORIENTBELL', 'PCJEWELLER', 'PRAJIND', 'PSPPROJECT', 'RADIOCITY', 'RECLTD', 'RPOWER', 'SADBHAV', 'SAFARIND', 'SBIN', 'SCHAND', 'SHAILY', 'SHRIRAMEPC', 'SNL', 'SPAL', 'SREEL', 'SYNCOM', 'SYNCOMF', 'TATASTLBSL', 'TECHNOFAB', 'UNIPLY', 'VARDHACRLC', 'VIAANINDUS', 'VIPIND', 'WELCORP', 'WELENT', 'WESTLIFE', 'LEMONTREE', 'SADBHIN', 'KELLTONTEC', 'VIVIDIND', 'IBVENTURES', 'IOB', 'MANAKSTEEL', 'REPCOHOME', 'SHREYANIND', 'WABAG', 'SIMPLEXINF', 'THOMASCOOK'],
    // selectedStocks: ['YESBANK', 'BCP', 'KUSHAL', 'EROSMEDIA', 'ORIENTBELL', 'ALOKINDS', 'RUBFILA', 'PENIND', 'PRAJIND', 'SHEMAROO', 'SPAL', 'BHAGIL', 'VIRINCHI', 'VIPIND', 'PARACABLES', 'ONGC', 'INNOVATIVE', 'UNIPLY', 'SBIN', 'TAKE', 'PCJEWELLER', 'GMDCLTD', 'IOC', 'SNL', 'SREEL', 'VARDHACRLC', 'VIAANINDUS', 'WELENT', 'JAGRAN', 'OIL', 'ADANITRANS', 'GOLDIAM', 'GAYAPROJ', 'NITINSPIN', 'MANAKSTEEL', 'REFEX', 'DHFL', 'SAFARIND', 'KITEX', 'WESTLIFE', 'SIMPLEXINF', 'BCLIL', 'ABFRL', 'TGVSL', 'SHREYANIND', 'MIRCELECTR-BE', 'USHAMART', 'GRAPHITE', 'HIRECT EVENT', 'EIHOTEL', 'DOLLAR EVENT', 'MENONBE', 'KNRCON', 'RPOWER', 'HTMEDIA', 'MULTIBASE', 'JAMNAAUTO', 'INDTERRAIN', 'ABAN', 'SINTEX', 'UDL', 'MUKANDLTD', 'HDIL', 'SHAILY']
    selectedStocks: ['ABFRL', 'ASHIKACR', 'BCLIL', 'BHAGIL', 'DHFL', 'DOLAT', 'FAZE3Q', 'GMDCLTD', 'GOLDIAM', 'HDIL', 'HIRECT', 'HMVL', 'INDIANB', 'INDINFO', 'INNOVATIVE', 'IOC', 'JAGRAN', 'JBFIND', 'JIYAECO', 'KITEX', 'MAHINDCIE', 'MANAKSTEEL', 'MENONBE', 'MITTAL', 'MUKANDLTD', 'MULTIBASE', 'OIL EVENT', 'ONGC', 'ORIENTHOT', 'PCJEWELLER', 'PENIND', 'PFC', 'PNB', 'PRAJIND', 'RAYMOND', 'REFEX', 'RPOWER', 'RRIL', 'RUBFILA', 'SADBHAV', 'SAFARIND', 'SEYAIND', 'SHAILY', 'SHEMAROO', 'SHK', 'SNL', 'SREEL', 'SUNDARAM', 'UNIONBANK', 'UNIPLY', 'VARDHACRLC', 'VIAANINDUS', 'VIPIND', 'WELENT', 'WESTLIFE', 'WPIL']
};




export default stockInitState;


